### ISSUE TITLE
Crowdsec mod

### ISSUE THREAD

**Issue by lordraiden** [linuxserver/docker-mods#349]
Is it normal that the bouncer last API pulls doesn't change? is this due to the live mode?
![imagen](https://user-images.githubusercontent.com/17175395/158265882-bc828212-55d6-4f80-89c4-be6619503cfe.png)

I have 4 hits per min aprox in my firewall from the bouncer to the cscli API
![imagen](https://user-images.githubusercontent.com/17175395/158266421-ccaf5a8f-469d-45c6-ac53-3ed9ec0f92b1.png)

**Comment by aptalca** [comment]
Wild guess, maybe `pull` is when it actually finds and implements an update? As opposed to querying the api and not seeing any updates

**Comment by j0nnymoe** [comment]
Also, wouldn't this be a question for crowdsec directly and not us?

**Comment by TheSpad** [comment]
My uneducated guess on this having played with a bunch of bouncers is that when something like a firewall bouncer does a pull of all the banned address to add them to its ruleset that updates the Last API Pull time, but when something like the nginx bouncer does a single-address query to see if that address is banned, it doesn't update the Last API Pull time.

But yes, it's a question for CrowdSec rather than us.

**Comment by lordraiden** [comment]
@TheSpad  could you reopen this?
For some reason this implementation of the bouncer doesn't update or do API pulls "correctly" despite this it works, but I guess this should be fixed

-------------------------------------------------------------------------------------------------------------------------------------------
 NAME               IP ADDRESS   VALID  LAST API PULL         TYPE                         VERSION                                         
-------------------------------------------------------------------------------------------------------------------------------------------
 swag               10.10.50.10  ✔️      **2022-03-14T21:21:17Z**  crowdsec-nginx-bouncer       v1.0.0                                          
 cloudflarebouncer  10.10.40.11  ✔️      2022-03-23T07:41:16Z  crowdsec-cloudflare-bouncer  v0.0.9-d93dd28911e1913589b15684c15c221f8c33a588 
-------------------------------------------------------------------------------------------------------------------------------------------

![imagen](https://user-images.githubusercontent.com/17175395/159648272-5e3900f2-898c-405c-ac13-b264e3461a17.png)

**Comment by TheSpad** [comment]
> @TheSpad could you reopen this? For some reason this implementation of the bouncer doesn't update or do API pulls "correctly" despite this it works, but I guess this should be fixed
> 
> ![imagen](https://user-images.githubusercontent.com/17175395/159648492-41db3e03-ecf0-4a15-b133-ee4a7999e26a.png)
> 
> ![imagen](https://user-images.githubusercontent.com/17175395/159648272-5e3900f2-898c-405c-ac13-b264e3461a17.png)

The not updating the last API pull is by design (of the bouncer, not the mod) when querying individual IP addresses so as not to cause a storm of db updates on high utilisation setups. If you run the bouncer in stream mode where it caches the whole ban list it will update the last pull time whenever it refreshes the cache.

There's an open feature request to do periodic updates to the last pull time even in live mode.

As for the dashboard, I don't believe that's anything specific to the mod, I'd raise it with crowdsec directly via their discord server, or a GitHub issue.
