### ISSUE TITLE
Crowdsec bouncer marked as inactive?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-mods#373]
I have the crowdsec mod added to my swag compose, swag is up, running, and serving all of my sites as per usual, but when I look at the crowsed dashboard it says the swag bouncer is inactive; anyone know why?

![image](https://user-images.githubusercontent.com/39491297/167940888-cd08d873-e892-4ae0-994e-0b51cb84854e.png)

![image](https://user-images.githubusercontent.com/39491297/167939971-18735d38-9c32-4748-9b79-933dd9087661.png)

**Comment by YouveGotMeowxy** [comment]
Yelllllllo?

**Comment by j0nnymoe** [comment]
The reason it's showing inactive is to prevent performance issues the live mode doesn't update the last API contact timestamp.

There are two types of bouncer operation - live and stream. Stream downloads the whole block db and applies it (like the firewall ones) whereas live looks up the address when it connects. They're changing it at some point soon to update if the timestamp is older than X so that it will show as active but not hammer the db with timestamp updates.
