### ISSUE TITLE
update linuxserver/jellyfin-opencl-intel to 22.08.22549 or newer

### ISSUE THREAD

**Issue by joaophi** [linuxserver/docker-mods#388]
Hi @aptalca

Could you run the [linuxserver/jellyfin-opencl-intel](https://github.com/linuxserver/docker-mods/tree/jellyfin-opencl-intel) workflow to update it [intel/compute-runtime](https://github.com/intel/compute-runtime) to a newer version? Hardware tone mapping is not working.
Their official container uses 22.08.22549 ([jellyfin/Dockerfile#L27](https://github.com/jellyfin/jellyfin/blob/0e1a41f7e938e415c32364ff1a4c97b8abab5fae/Dockerfile#L27)) and your mod is at 21.37.20939.

Thanks for your great work!

**Comment by aptalca** [comment]
Hmm, we were supposed to create an external trigger for this to trigger builds on upstream releases but it seems we forgot.

I think it would be better to have this kid install from the Intel apt repo rather than get the debs from their GitHub releases.

Actually, now that jellyfish is stable with tone mapping, we can also integrate the opencl into the main image and deprecate this mod.

I'll give it some thought and discuss with the team.

**Comment by aptalca** [comment]
Just to circle back to this. The main jellyfin dev who oversees the hardware acceleration bits advised staying on the current version the mod is on. Intel drivers can break functionality. He let us know he will ping us when it needs to be updated so we won't implement a trigger for auto updates.

**Comment by aptalca** [comment]
We just pushed an update to the mod that properly versions. And we enabled a trigger to auto build each new version.
