### ISSUE TITLE
only amd64?

### ISSUE THREAD

**Issue by lavaguy1** [linuxserver/docker-mods#44]
Is there a technical reason that docker-mods only work on amd64, or is there a chance that some of them will be made available for arm? In particular, it'd be good to get the lazylibrarian-ffmpeg mod to work with lazylibrarian-arm...

Thanks

**Comment by aptalca** [comment]
It works on arm

**Comment by lavaguy1** [comment]
sorry! was just me being overcautious, i guess - in the docker web site it says only Linux/amd64 under Arch...

Thanks so much for the quick reply!

**Comment by aptalca** [comment]
Where do you see that exactly?

**Comment by lavaguy1** [comment]
on hub.docker.com
![image](https://user-images.githubusercontent.com/21985291/82764019-2b365a80-9e0c-11ea-8b14-d0e4d89950cb.png)

**Comment by lavaguy1** [comment]
while we are at it... any chance you guys will start maintaining a Calibre image for arm? I know it's a big ask...

**Comment by aptalca** [comment]
ahhh, that doesn't really mean anything because the that image layer doesn't even contain an OS, it's just a `FROM scratch` image with some added files. The container downloads that tarball and extracts to the root.

Calibre binary is x86_64 only. If and when they start releasing it for arm, then we can add it.

**Comment by lavaguy1** [comment]
i get it. I figured as much when it started doing that at the start of
LazyLibrarian. it's just a little confusing. Thanks again for the quick
help!
