### ISSUE TITLE
Why does dashboard expose its own domain by itself?

### ISSUE THREAD

**Issue by labmonkey** [linuxserver/docker-mods#511]
In the dashboard-mod in the file https://github.com/linuxserver/docker-mods/blob/swag-dashboard/root/etc/cont-init.d/98-dashboard-config you can see the following script:
```
if [ ! -f /config/nginx/proxy-confs/dashboard.subdomain.conf ]; then
  cp /dashboard/dashboard.subdomain.conf.sample /config/nginx/proxy-confs/dashboard.subdomain.conf
fi
```
I don't understand this behavior. The whole SWAG provides multiple .sample configuration file for many domains but none of them ever is automatically exposing itself. I think that the users got used to this idea that they can/should optionally copy any of the samples and approach it in more of a DIY way and no one has issues with that, it's just how you configure SWAG. That's why I found it surprising to see that I have dashboard config exposed even that I did not want to do that. I understand that there are deny rules inside but still why not just write in documentation that this file has to be copied if you want to use domain to access it just like everywhere else?

**Comment by aptalca** [comment]
The regular proxy confs are shipped with the image by default. You need to specifically enable them if you want to use them.

The dashboard mod does not come with the image and needs to be installed specifically.

> That's why I found it surprising to see that I have dashboard config exposed even that I did not want to do that.

Then why did you install the mod?

It's only exposed on the lan, which you can change yourself

**Comment by labmonkey** [comment]
Sorry I think I wrote this in a bit confusing way. What I was trying to say is that I can access my dashboard from the public internet based on the default config. In the meantime I've investigated the issue and now I see why. 
The reason is that the dashboard mod is always automatically enabling the `dashboard.subdomain.conf` and that file is containing the following lines:
```
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
```
At first look you could say that it will only allow lan access but to my surprise typing `https://dashboard.<mydomain>.com` allowed me to access it. The reason is because I use Cloudflare and in this case the IPs reported to nginx are different. Cloudflare by default will be shown as docker internal IPs, for example in my case the clients in the logs have IP `172.18.0.1` (same thing when you for example run `getenv('REMOTE_ADDR')` in php). But nothing new here as thats why the `swag-cloudflare-real-ip` mod exists. 

So here is the issue. It is possible to use Cloudflare with dashboard mod enabled and unintentionally expose the dashboard to the internet because of the `allow` configuration above and the way Cloudflare works. Considering the fact that `swag-cloudflare-real-ip` is not a mandatory mod and the proxy can run without it (if somebody does not need real ips) I think this is a security issue as users can be unaware of it.

In the meantime my 'workaround' is to either enable `swag-cloudflare-real-ip` (which I do anyway) or to provide my own `dashboard.subdomain.conf` where I remove the lines `allow 172.16.0.0/12;`.

**Comment by beauso** [comment]
Agreed. I don't want to be forced to expose the dashboard over my public SWAG proxy and be at the mercy of allow/deny rules. It may be blocking connections but it is still exposed.

In my case, I'd much rather remove any forced proxy-config on my public SWAG instance and instead forward this on my internal SWAG instance. I've unfortunately had to remove this mod for now as I'm not comfortable with it being exposed for similar reasons as @labmonkey mentioned.

**Comment by aptalca** [comment]
Let's back up for a sec.

The intention is _not_ `to have nginx automatically expose the dashboard publicly` so there is no such thing as ` forced to expose the dashboard over my public SWAG proxy`.

If it is happening to you, that's because you have a faulty nginx config (other issues) that needs to be addressed.

If all requests coming to nginx look like they are from the same IP address, that is a problem that can cause many issues including breaking fail2ban, crowdsec, and all geoip based measures, as well as this issue you're experiencing.

You keep saying `using Cloudflare`, but I don't know what you mean. Cloudflare has many different services. I use them for dns. I am assuming you mean `cloudflared`, their tunnel container? If so, you need to set it up properly with nginx in SWAG so it presents the source IPs correctly. The cloudflare-real-ip mod does that and is not a `workaround`, it is the real thing you need to use (you can also set those real ip headers manually in your nginx config). That's what the Cloudflare docs recommend. https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs

Alternatively, the dashboard proxy conf has various auth options if you don't want to manage access by IP only.

> Considering the fact that swag-cloudflare-real-ip is not a mandatory mod and the proxy can run without it (if somebody does not need real ips) I think this is a security issue as users can be unaware of it.

It's not mandatory because most users don't use cloudflared or put any other proxy in front of SWAG. If you are doing that, then not setting the real ip headers (or not using the mod) is actually a security issue.

**Comment by beauso** [comment]
### My use case for disabling automatic `dashboard.subdomain.conf`
I'm using Cloudflare for DNS, allow me to describe my situation (which is different than @labmonkey's, but ultimately boils down to not wanting to rely on ACLs/default proxied behavior):

- `mydomain.com` points to my public SWAG instance.
- `int.mydomain.com` points to my internally resolvable DNS, which points to my internal SWAG instance. 

I have separated these two because I'm not comfortable relying purely on ACLs to secure access to internal services, and having this configuration greatly limits the blast radius of a mistake caused by myself or from other possible changes in configuration.

Since I'm interested in visualising logs from my public SWAG instance, I'd much rather have the dashboard proxy configuration on my internal SWAG instance. However, the current behaviour of enabling `dashboard.subdomain.conf` makes this problematic for me as by default, it's already "exposed" on the public SWAG instance thus giving me no peace of mind by opting to handle it via my internal proxy instead.

### Other thoughts regarding disabling `dashboard.subdomain.conf`
Furthering upon the point you made about setting the `CF-Connecting-IP` header via tunneled traffic I think the default behaviour of enabling `dashboard.subdomain.conf` without explicit consent from the user (so either manually or via a separate env var) assumes a secure configuration and is worth reconsidering; even if it does not presently affect me. For example a user could use the mod, access the service internally over `:81` and not even be aware that this is accessible over `dashboard.*`, since as pointed out in the original issue message, it goes against the convention of users manually "exposing" services.

**Comment by aptalca** [comment]
Perhaps I didn't make myself clear. If your SWAG is configured properly, the dashboard is _not_ exposed publicly. It is only accessible from the same lan.

> enabling dashboard.subdomain.conf without explicit consent from the user

you manually installed the mod, which is consent for publishing locally

> access the service internally over :81 and not even be aware that this is accessible over dashboard.*

The readme states that it is available via the subdomain locally: https://github.com/linuxserver/docker-mods/tree/swag-dashboard#enable

**Comment by drizuid** [comment]
Closing, this is a user misconfiguration, not a problem with the dashboard mod (which aptalca and I both use with cloudflare dns and do not have this issue). We can not fix user caused issues with any github changes. The OP stopped replying after learning this was their mistake so this ghi is no longer relevant.
