### ISSUE TITLE
flac2mp3 - Endless Loop

### ISSUE THREAD

**Issue by samcro1967** [linuxserver/docker-mods#568]
Trying this mod for the first time.  I seem to be stuck in an endless loop.  Lidarr grabs some media.  It is converted from flac to mp3, the flac files are deleted, and then lidarr sees them as missing and grabs them again.  Seems like lidarr is not updating after files are converted to mp3.  Hoping I am missing something.

**Comment by TheCaptain989** [comment]
It should not do that.  What version of Lidarr are you on?  Also, could you post your flac2mp3.txt log, please?

**Comment by samcro1967** [comment]
Version 1.1.3.2953

**Logs**
https://pastebin.com/ZMWChbZX

**Comment by TheCaptain989** [comment]
Thanks!
Lidarr is clearly re-downloading the same albums.  However, also note that my script is saying that it is communicating with the Lidarr API and it does to return an error.  I'm going to need more detailed logs to troubleshoot further.

Can you please run my script in debug mode (with the -d option)?  The easiest way is to select the `flac2mp3-debug.sh` script in Lidarr.

**Comment by TheCaptain989** [comment]
Hmmm.  I've not tested it with this version of Lidarr.  I'm running 1.0.2.2592 myself.  Let me see what I find in my testing, but from the logs you've posted so far it looks like my script is being called and executing and terminating correctly.

**Comment by TheCaptain989** [comment]
I just tested Lidarr v1.1.3.2960 with the exact same 2 albums from your logs.  My script worked perfectly for me, with a small exception that of a 'chown' error in the Lidarr logs (I'll have to look at that later), but that had no impact on the conversion or Lidarr seeing the new MP3 files.

I'm thinking it may be your Quality Profile in Lidarr.  If you're using **Lossless**, for example, Lidarr will download FLAC files, then my script will convert them to a lossy MP3 format and tell Lidar that it did that.  Lidarr could then try to upgrade the MP3 files that my script just created.  That could create a looping situation.  Your `Lidarr.txt` log would tell you for sure.

**Comment by samcro1967** [comment]
The lidarr container did update today, but is showing the same lidarr version.  I re-enabled the script in debug mode and of course it did not happen today.  It did the download and conversion.  Even though everything seems to have executed properly and the files are on disk and in the right place, lidarr is showing no files present.  I am sure if I do a manual import, they will be discovered and then show up.  Did not do that yet.  Wasn't sure if there is something you might want to see or have me try first.

I have one profile setup that looks for unknown, mp3's, and lossless.  Mp3's is a group of all mp3 quality profiles >= MP3-128.

**Comment by TheCaptain989** [comment]
> I am sure if I do a manual import, they will be discovered and then show up.

If the files are there, all you should have to do is a Refresh & Scan; no import needed.

In my testing, my script triggers the re-scan and Lidarr saw the MP3 files.  Though, I am still curious why that's not happening in your setup, it seems like my script is working properly.

As a side note, it looks like v1.1 is still in development, with no stable release.  The team has published several pre-releases, with [1.1.2.2935](https://github.com/Lidarr/Lidarr/releases/tag/v1.1.2.2935) being the latest one.  The 1.1.3 train is only days old and still doing nightly builds and is apt to change frequently, and could have bugs from one upgrade to the next.  You may want to consider going to a more stable version of Lidarr.

**Comment by samcro1967** [comment]
I tried a Refresh & Scan and they are not picked up.  If I try an import, it sees the files and gives me the ability to import them.  I have not done that yet though on the most recent test, but it worked before to stop the infinite loop.  Starting to think like you say that it might be an issue with nightly code base and something with my setup.  I will try stable when I get some time tomorrow and see if I get a different behavior.

**Comment by TheCaptain989** [comment]
Have you had any recurrences?  I haven't been able to duplicate your observed behavior.

**Comment by samcro1967** [comment]
I am traveling this week for business so I haven had a chance to test and it has not pulled anything on its own.  I will test in the next few days and report back once I am home.

**Comment by samcro1967** [comment]
Just did a test and it is not happening now.  Maybe an update to the LSIO container????  Seems to work as expected now.  Thanks for the help!

**Comment by TheCaptain989** [comment]
You're welcome.

**Comment by samcro1967** [comment]
I had a few that worked and now I have another one in an endless loop.

**flac2mp3 logs**
https://pastebin.com/JMHtqM23

**app logs**
https://pastebin.com/fQukdGFc

**Comment by TheCaptain989** [comment]
Thank you!

From your logs, it appears that this is what's happening:

1. Lidarr sees the missing album (in this case: TYR - Black Sabbath)
2. Lidarr uses NZBgeek to search for the album and tells SABnzbd to download the album in FLAC format
3. Lidarr updates its own database once the album is downloaded
4. Lidarr calls a `beets_import.sh` script, which errors on its own lines 15 and 16 with a `beet: command not found` error
5. Lidarr calls my `flac2mp3.sh` script, which converts the FLAC files to MP3 files
6. After the conversion, flac2mp3.sh calls Lidarr's RefreshArtist API.
7. Lidarr begins to rescan the artist folder by logging `Info|RefreshArtistService|Updating Info for Black Sabbath`
8. `flac2mp3.sh` occasionally times out after waiting 15 seconds for the rescan to complete.  In any event, my script completes normally.
9. After the rescan, Lidarr starts a DiskScan on its own by logging `Info|DiskScanService|Scanning /music/`
10. Lidarr logs the following error twice, about 2 minutes apart:
```
Error|CommandExecutor|Error occurred while executing task RescanFolders

[v1.1.3.2964] System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```
11. Lidarr's disk scan never completes and its database is never updated, so about 9 minutes later when the RSS Sync task kicks off, because it thinks there are no album tracks, it starts the whole process again.

Here are my thoughts:
- My flac2mp3.sh script is working as intended.
- From step 4 above, you have a Custom Script configured called beets_import.sh that it throwing its own errors.  However, this doesn't appear to be related to the looping.
- **The fact that Lidarr has a task crashing in step 10 is the cause of the looping.**  The rescan never completes after my script converts the track files to MP3, so it doesn't know they are there.
- **Lidarr is running our of memory**, but I can't determine the root cause of this from the logs.  It could be the version of Lidarr you're running is unstable, as I indicated in my older posts.
- The logs from step 9 seem to indicate that you _might_ have your root music folder `/music/` configured twice.  Check your Settings > Media Management.  Perhaps this is contributing to the crash?  I really can't say for sure.

I would recommend that you:
- [ ] Check that your root music folder is only configured once.
- [ ] Downgrade your version of Lidarr to 1.0.2
- [ ] Check your beets_import.sh script for the cause of its error

I hope this helps!

P.S. - I've never understood why Lidarr insists on kicking off a DiskScan after my script calls RefreshArtist.  It takes _forever_ on large libraries.  I'm thinking there is some room for improvement on my end.  Maybe there's a way I can just tell Lidarr the name of each new filename directly.  Maybe in my next script version.

**Comment by samcro1967** [comment]
Beets script is disabled
Doubled the amount of memory allocated to Lidarr.
Confirmed that music folder is only setup once in Settings > Media Management.

If I still see the issue, I will downgrade to 1.0.2 next.

**Comment by TheCaptain989** [comment]
@samcro1967 do you have an update on your issue?

**Comment by samcro1967** [comment]
Increasing the memory for Lidarr resolved the last issue.  Thanks for your help!
