### ISSUE TITLE
Flood-ui not working with sonnar and radarr.

### ISSUE THREAD

**Issue by P6g9YHK6** [linuxserver/docker-mods#586]
if enabled it prevent radarr and sonarr to see if a download is completed. (*arr will show the correct "100%" but not the status "completed")
and will not import the files once downloaded.

i tried restarting all my containers to no avail...
the only solution was to disable the mod.

**Comment by P6g9YHK6** [comment]
same issue with transmission-transmissionic

**Comment by thespad** [comment]
All the mods do is copy the theme files into the container and set the WEB_HOME environment variable. If there's an issue with the theme(s) breaking 3rd party integrations then that needs to be raised with the upstream theme (https://github.com/johman10/flood-for-transmission or https://github.com/6c65726f79/Transmissionic/).

**Comment by johman10** [comment]
@thespad since @P6g9YHK6 is saying that the issue also occurs with transmission-transmissionic I doubt this is really related to the themes.

I would also be very suprised if this is any of the themes are causing issues though, because @thespad is right, all this does is copy the files from Github and pointing to them with the TRANSMISSION_WEB_HOME variable.

@P6g9YHK6 are you sure this is caused by Transmission and not via some other kind of configuration?
