### ISSUE TITLE
Q: can docker mod block startup of the main service

### ISSUE THREAD

**Issue by laur89** [linuxserver/docker-mods#596]
I'm trying to find okay-ish solution for the dreaded [multiple domains & certs](https://github.com/linuxserver/docker-swag/issues/33#issuecomment-721281084) issue for swag.

Would implementing this as a docker mod be feasible? If mods can block startup of swag, then I can't see any problems - mod startup would update the certs for extra domains, and then swag would start up, picking up the extra certificates.

Is this feasible?

**Comment by aptalca** [comment]
Anything is possible. Have at it.

**Comment by thespad** [comment]
OOTB mod init steps will run after built-in init steps (but before services). You'd have to rejig things so that your mod components ran beforehand. It's possible, but fiddly and obviously not something we would support.

In theory a mod can completely rearrange the container init process, with the caveat that it can't *delete* anything that's already in place (though it can replace it).

**Comment by laur89** [comment]
That was sort of the core of my original question -- should I tap into some S6 feature to make sure the new cert update logic runs _before_ nginx is started?

**Comment by thespad** [comment]
If you just want to run it before the nginx service starts then you don't need to do anything fancy, mod init scripts run before services (mod *services*) run in parallel with built-in services.

If you want to change how the current init functions it's more complicated.
