### ISSUE TITLE
openssh-server-ssh-tunnel's last update ironically breaks ssh tunnels

### ISSUE THREAD

**Issue by azertyfun** [linuxserver/docker-mods#713]
#670 broke the openssh-server-ssh-tunnel mod. It [removes the `root/etc/cont-init.d/98-ssh-tunnel-config` file](https://github.com/linuxserver/docker-mods/commit/711a3d1b18e58d99843c6405596448241e0c315d#diff-c69243d74bbd474013fe32470796659bfb0e5f5daa0074c2f7a9bfd6cc92ea3fL1) which leaves `AllowTcpForwarding no`, preventing ssh tunnels from being established.

I'm assuming that's not intentional, especially given that the description of the PR does not match the change? If anyone else is looking for a solution, it's simply to roll back to the previous version: `DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel-a2fbf27cc43098d02a528e2b6eff67e64451b340`

(Personal lesson learned: don't use `DOCKER_MODS` without using an immutable tag or your service may go down unexpectedly... thankfully we aren't using ssh tunnels in prod)

**Comment by Roxedus** [comment]
The logic should still be in place, just be running in an earlier stage of the [init process](https://github.com/linuxserver/docker-mods/blob/openssh-server-ssh-tunnel/root/etc/s6-overlay/s6-rc.d/init-mod-openssh-server-ssh-tunnel-setup/run). If this logic is failing, some logs would be appreciated.

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-mods/blob/a2fbf27cc43098d02a528e2b6eff67e64451b340/root/etc/cont-init.d/98-ssh-tunnel-config was removed because it's part of the old v2 mod logic that hasn't applied to any images built in the last ~9 months. The logic is now handled by https://github.com/linuxserver/docker-mods/blob/openssh-server-ssh-tunnel/root/etc/s6-overlay/s6-rc.d/init-mod-openssh-server-ssh-tunnel-setup/run, which has been in place since v3 mods were introduced last year.

If it's stopped working for you that suggests you're using an OpenSSH image that's 9+ months old and lacks the v3 mod hooks.

**Comment by azertyfun** [comment]
Thanks for the speedy response! Looks like the issue is indeed that we're using an overly old openssh-server version (a year old, not sure how this ended up in there considering we've added this service much more recently than that... anyway).

Sorry for the trouble!
