### ISSUE TITLE
Multi-arch mods?

### ISSUE THREAD

**Issue by TheCaptain989** [linuxserver/docker-mods#92]
I'm the maintainer of the radarr-striptracks mod.  I also have an as yet unsubmitted mod called [lidarr-flac2mp3](https://github.com/TheCaptain989/lidarr-flac2mp3) that I had a user request an [ARM build](https://hub.docker.com/repository/docker/thecaptain989/lidarr-flac2mp3/tags) for.  I managed to get it working with Travis CI and it was easy enough I thought I'd ask if there is any interest in multi-arch builds in general.

You can check out the [.travis.yml](https://github.com/TheCaptain989/lidarr-flac2mp3/blob/master/.travis.yml) and the [Dockerfile.arm64](https://github.com/TheCaptain989/lidarr-flac2mp3/blob/master/Dockerfile.arm64) that make it work (though I'm probably preaching to the choir 😉).

**Comment by Roxedus** [comment]
I fail to see how your Dockerfile is arch dependent. It pulls the x86 variant regardless (really it just pulls the tag you give it), and your mod uses the OS package manager to install binaries, so it handles that for you.

**Comment by aptalca** [comment]
Yeah, the two dockerfiles you have push the exact same image/tarball, which contains one init script and 2 sh scripts, that's all. They're just using two different build images to copy the files over, but those build images are discarded.

The way we handle mods is not arch dependent at all. The single layer images are just handled as a tarball, that's all.

**Comment by nemchik** [comment]
A few notes here.

1. Your mod uses a build stage but doesn't actually need one. All of the action is happening in scripts that run inside the container being modded (not during the build of the mod image) therefore you don't need a build stage in your case.
2. Your scripts account for both alpine (apk) and ubuntu (apt) although since your mod is specifically for lidarr it should only need apt (our lidarr image uses an ubuntu base). It doesn't hurt to have the extra logic in there, but it'll never fire unless we change the base image (not too likely).
3. Because the scripts that do the work run inside the container being modded they will install the correct architecture specific package for the running container, and therefore the mod itself does not need to be multi-arch.

The purpose of the mod is to bring only the new required code into an existing image. In your case if you were to apply that mod to an image with an alpine base you would actually be replacing the base OS since your build stage contains an OS (ubuntu) and is being copied at runtime when the mod is applied to the container being modded.

If you need help slimming this down please feel free to ask on our discord. I'm going to close this issue as the topic intended is not valid, but I do hope you visit our discord and chat about continuing development of your mod.
